Time loop and toggle all pins functionality
Added the toggle switch to activate/deactivate all the pins at once. Also modified the endless loop and added wrapper functions to arduino methods.

Please check code in the app designer: Look for the error:

''Error using InSitu_BST_SoftwareV8
Error: File: InSitu_BST_SoftwareV8.mlapp Line: 759 Column: 61
Invalid expression. When calling a function or indexing a variable, use parentheses. Otherwise, check for
mismatched delimiters.'